import TablaAdmin from "@/components/TablaAdmin";
import TablaCitas from "@/components/TablaUsers";
import { useUser } from "@clerk/nextjs";
import Head from "next/head";

const Reservaciones = () => {
  const { isSignedIn, user } = useUser();
  if (!isSignedIn) {
    return null;
  }
  const adminId = "user_2UEZfeK4SpGi1THODGZpvTCF9HW";

  return (
    <>
      <Head>
        <title>Reservaciones</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/k_S.svg" />
      </Head>
      {user?.id === adminId ? <TablaAdmin /> : <TablaCitas />}
    </>
  );
};

export default Reservaciones;
